[package]
name = "serde_spanned"
version = "1.0.3"
description = "Serde-compatible spanned Value"
categories = ["encoding", "parser-implementations", "parsing", "config"]
keywords = ["serde", "span"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/toml-rs/toml/compare/{{tag_name}}...HEAD", exactly=1},
]

[features]
default = ["std", "serde"]
alloc = ["serde_core?/alloc"]
std = ["alloc", "serde_core?/std"]
serde = ["dep:serde_core"]

[dependencies]
serde_core = { version = "1.0.225", optional = true, default-features = false }

[dev-dependencies]
serde = "1"
serde_derive = "1"
serde-untagged = "0.1"
toml = { path = "../toml" }

[lints]
workspace = true
